Ablility to update all settings with a Map
benbarkay/htmltopdf-java pull request #16
Opened 2018-11-28 12:04 UTC by dariosilva

Since we can have multiples options to configure the generation of pdfs, I think that is useful to make a Map structure with the settings a pass it to the classes: HtmlToPdf and HtmlToPdfObject.

This way we can load a bunch of settings (e.g. from external properties files) in a few lines of code.

So, I propose to add two new methods to allow the update the settings with a Map.

2018-11-28 14:29 UTC, benbarkay requested changes
Thank you for the PR, I will gladly merge once the changes are made :)

2018-11-29 10:05 UTC, dariosilva commented on src/main/java/io/woo/htmltopdf/HtmlToPdf.java
> +    public HtmlToPdf setting(Map<String,String> settings) {
Yes, you are right! I made the changes in the new commit: https://github.com/wooio/htmltopdf-java/pull/16/commits/b31d8570a7cff7567c4417ab93bcff8a9222cf27#diff-84732fa7114c570fa208a481f5fabc86R31

2018-11-29 10:05 UTC, dariosilva commented on src/main/java/io/woo/htmltopdf/HtmlToPdf.java
> +        this.settings = settings;
Solved. Many thanks.

2018-11-29 10:07 UTC, dariosilva commented on src/main/java/io/woo/htmltopdf/HtmlToPdfObject.java
> +    public HtmlToPdfObject setting(Map<String,String> settings) {
Changes made at the new commit: https://github.com/wooio/htmltopdf-java/pull/16/commits/b31d8570a7cff7567c4417ab93bcff8a9222cf27#diff-a539f6324aadc3006396f439efd0d005R24 and https://github.com/wooio/htmltopdf-java/pull/16/commits/b31d8570a7cff7567c4417ab93bcff8a9222cf27#diff-a539f6324aadc3006396f439efd0d005R48

2018-11-29 22:57 UTC, benbarkay approved these changes
There are still a couple of things that bug me, but I'll change them myself before releasing.
Thank you for your contribution :)

2018-11-29 22:58 UTC, merged

2018-11-30 09:32 UTC, dariosilva commented
Thank you @benbarkay :)